[buildPlans.IosevkaSans]
family         = "Iosevka Sans"
description    = "Sans-Serif Style"
snapshotFamily = "Iosevka Sans"

[buildPlans.IosevkaSans.variants.design]
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "closed-serifless"
six = "open-contour"
nine = "open-contour"
zero = "oval-tall-slashed"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifless"
capital-q = "crossing"
a = "double-storey-toothless-rounded"
b = "toothless-corner-serifless"
c = "serifless"
d = "toothless-corner-serifless"
f = "flat-hook-serifless"
g = "single-storey-flat-hook-earless-corner"
i = "hooky"
j = "flat-hook-serifed"
l = "serifed-flat-tailed"
m = "earless-corner-double-arch-serifless"
n = "earless-corner-straight-serifless"
p = "earless-corner-serifless"
q = "earless-corner-straight-serifless"
r = "earless-corner-serifless"
t = "flat-hook"
u = "toothless-corner-serifless"
y = "straight-turn-serifless"
lower-eta = "earless-corner-serifless"
lower-lambda = "straight-turn"
lower-mu = "toothless-corner-serifless"
lower-xi = "rounded"
cyrl-a = "double-storey-toothless-corner"
cyrl-er = "earless-corner-serifless"
cyrl-capital-u = "straight-turn-serifless"
cyrl-u = "straight-turn-serifless"
asterisk = "penta-low"
paren = "large-contour"
at = "fourfold-solid-inner"
percent = "dots"
question = "corner-flat-hooked"
micro-sign = "toothless-corner-serifless"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted-dotted"
lig-plus-chain = "with-notch"
lig-double-arrow-bar = "with-notch"
lig-single-arrow-bar = "with-notch"
